name: Download artifact
description: 'Download docker image created in secure-docker-build'

inputs:
  image_digest:
    description: "Eg cc982954903747ca353f122677dfe1b35df8d710c2d6b00ef2a1f8569f38fa27"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image_digest }}
        path: ${{ runner.temp }}

    - name: Load image
      shell: bash
      run:
        docker load --input ${{ runner.temp }}/${{ inputs.image_digest }}.tar | tee load.log
