name: Download artifact
description: 'Download docker image created in secure-docker-build'

inputs:
  IMAGE_NAME:
    required: true
    type: string
  IMAGE_DIGEST:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.IMAGE_DIGEST }}
        path: ${{ runner.temp }}

    - name: Load image
      shell: bash
      run:
        cat ${{ runner.temp }}/${{ inputs.IMAGE_DIGEST }}.tar | docker import - ${{ inputs.IMAGE_NAME }}
