name: Download artifact
description: 'Download docker image created in secure-docker-build'

inputs:
  image_digest:
    description: "Eg cc982954903747ca353f122677dfe1b35df8d710c2d6b00ef2a1f8569f38fa27"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image_digest }}
        path: ${{ runner.temp }}

    - name: Setup Kosli CLI
      uses: kosli-dev/setup-cli-action@v2
      with:
        version: ${{ vars.KOSLI_CLI_VERSION }}

    - name: Load image, verify
      shell: bash
      run: |
        docker load --input ${{ runner.temp }}/${{ inputs.image_digest }}.tar | tee load.log
        # eg load.log == 'Loaded image: cyberdojo/web:03b8aa5'
        IMAGE_NAME="$(cut -d ' ' -f 3 load.log)
        FINGERPRINT="$(kosli fingerprint "${IMAGE_NAME}" --artifact-type=docker --debug=false)
        [ "${{ inputs.image_digest }}" == "${FINGERPRINT}" ]
